name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  drift: ^2.7.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.8
  path: ^1.8.3


  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.7.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/financialTracking.db